resource_types:
- name: slack-alert
  type: docker-image
  source:
    repository: arbourd/concourse-slack-alert-resource


resources:
- name: notify
  type: slack-alert
  source:
    url: https://hooks.slack.com/services/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
- name: node-app
  type: git
  source:
    uri: https://github.com/mar00nie/express-status-monitor.git
    branch: master


jobs:
  - name: run-pipeline
    public: true
    plan:
    - get: node-app
      trigger: true
    - put: notify
      params:
        alert_type: started
    - task: build-app
      file: node-app/task-node.yml
      on_success:
        put: notify
        params:
          alert_type: success
      on_failure:
        put: notify
        params:
          alert_type: failed
